name: Update .luacheckrc

on:
  push:
    branches:
      - 'main'
    paths:
      - '.luacheckrc_header'
      - '.github/workflows/main.yml'
  schedule:
    - cron:  '30 5,17 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate new .luacheckrc
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Rulesets
    - name: Clone FG-Unofficial-Developers-Guild/CoreRPG
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/CoreRPG
        path: .fg/rulesets/CoreRPG
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/2E
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/2E
        path: .fg/rulesets/DND2E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/3.5E
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/3.5E
        path: .fg/rulesets/DND35E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/4e
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/4e
        path: .fg/rulesets/DND4E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/5e
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/5e
        path: .fg/rulesets/DND5E
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/PFRPG
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/PFRPG
        path: .fg/rulesets/PFRPG
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/PFRPG2
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/PFRPG2
        path: .fg/rulesets/PFRPG2
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    - name: Clone FG-Unofficial-Developers-Guild/SFRPG
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/SFRPG
        path: .fg/rulesets/SFRPG
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    # bmos extensions
    - name: Clone FG-Unofficial-Developers-Guild/FG-FG-CoreRPG-Extraplanar-Containers
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/FG-CoreRPG-Extraplanar-Containers
        path: .fg/extensions/FG-CoreRPG-Extraplanar-Containers
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-Ammunition-Manager
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/FG-Ammunition-Manager
        path: .fg/extensions/FG-Ammunition-Manager
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-HitMargins
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/FG-HitMargins
        path: .fg/extensions/FG-HitMargins
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-CoreRPG-Party-Inventory-Weight
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/FG-CoreRPG-Party-Inventory-Weight
        path: .fg/extensions/FG-CoreRPG-Party-Inventory-Weight
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-CoreRPG-Party-Inventory-Identified
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/FG-CoreRPG-Party-Inventory-Identified
        path: .fg/extensions/FG-CoreRPG-Party-Inventory-Identified
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-CoreRPG-Moon-Tracker
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/FG-CoreRPG-Moon-Tracker
        path: .fg/extensions/FG-CoreRPG-Moon-Tracker
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-Aura-Effect
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/FG-Aura-Effect
        path: .fg/extensions/FG-Aura-Effect
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone FG-Unofficial-Developers-Guild/FG-24-Hour-Clock
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/FG-24-Hour-Clock
        path: .fg/extensions/FG-24-Hour-Clock
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}

    # Other dev's extensions
    - name: Clone FG-Unofficial-Developers-Guild/FG-ClockAdjuster
      uses: actions/checkout@v4
      with:
        repository: FG-Unofficial-Developers-Guild/FG-ClockAdjuster
        path: .fg/extensions/FG-ClockAdjuster
        fetch-depth: 0
    - name: Clone rhagelstrom/BetterCombatEffects
      uses: actions/checkout@v4
      with:
        repository: rhagelstrom/BetterCombatEffects
        path: .fg/extensions/BetterCombatEffects
        fetch-depth: 0
    - name: Clone Farratto/GoBigOrGoGnome
      uses: actions/checkout@v4
      with:
        repository: Farratto/GoBigOrGoGnome
        path: .fg/extensions/GoBigOrGoGnome
        fetch-depth: 0
    - name: Clone SirMotte/FGU-Theme-Hearth
      uses: actions/checkout@v4
      with:
        repository: SirMotte/FGU-Theme-Hearth
        path: .fg/extensions/FGU-Theme-Hearth
        fetch-depth: 0
    - name: Clone rhagelstrom/Turbo
      uses: actions/checkout@v4
      with:
        repository: rhagelstrom/Turbo
        path: .fg/extensions/Turbo
        fetch-depth: 0
    - name: Clone rhagelstrom/FranklyNot
      uses: actions/checkout@v4
      with:
        repository: rhagelstrom/FranklyNot
        path: .fg/extensions/FranklyNot
        fetch-depth: 0
    - name: Clone rhagelstrom/PowerUp
      uses: actions/checkout@v4
      with:
        repository: rhagelstrom/PowerUp
        path: .fg/extensions/PowerUp
        fetch-depth: 0
    - name: Clone rhagelstrom/Exhausted
      uses: actions/checkout@v4
      with:
        repository: rhagelstrom/Exhausted
        path: .fg/extensions/Exhausted
        fetch-depth: 0
    - name: Clone rhagelstrom/ChatAestheticsConfigurator
      uses: actions/checkout@v4
      with:
        repository: rhagelstrom/ChatAestheticsConfigurator
        path: .fg/extensions/ChatAestheticsConfigurator
        fetch-depth: 0
    - name: Clone rhagelstrom/ArcaneWard
      uses: actions/checkout@v4
      with:
        repository: rhagelstrom/ArcaneWard
        path: .fg/extensions/ArcaneWard
        fetch-depth: 0
    - name: Clone rhagelstrom/EffectiveInitiative
      uses: actions/checkout@v4
      with:
        repository: rhagelstrom/EffectiveInitiative
        path: .fg/extensions/EffectiveInitiative
        fetch-depth: 0
    - name: Clone rhagelstrom/HighVariance
      uses: actions/checkout@v4
      with:
        repository: rhagelstrom/HighVariance
        path: .fg/extensions/HighVariance
        fetch-depth: 0
    - name: Clone rhagelstrom/LifeLedger
      uses: actions/checkout@v4
      with:
        repository: rhagelstrom/LifeLedger
        path: .fg/extensions/LifeLedger
        fetch-depth: 0
    - name: Clone rhagelstrom/Pets
      uses: actions/checkout@v4
      with:
        repository: rhagelstrom/Pets
        path: .fg/extensions/Pets
        fetch-depth: 0
    - name: Clone rhagelstrom/BetterCombatEffectsGold
      uses: actions/checkout@v4
      with:
        repository: rhagelstrom/BetterCombatEffectsGold
        path: .fg/extensions/BetterCombatEffectsGold
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone farratto/WalkThisWay
      uses: actions/checkout@v4
      with:
        repository: farratto/WalkThisWay
        path: .fg/extensions/WalkThisWay
        fetch-depth: 0
    - name: Clone farratto/JackOfAllThings
      uses: actions/checkout@v4
      with:
        repository: farratto/JackOfAllThings
        path: .fg/extensions/JackOfAllThings
        fetch-depth: 0
    - name: Clone farratto/WinnowingPursuits
      uses: actions/checkout@v4
      with:
        repository: farratto/WinnowingPursuits
        path: .fg/extensions/WinnowingPursuits
        fetch-depth: 0
    - name: Clone farratto/Blink
      uses: actions/checkout@v4
      with:
        repository: farratto/Blink
        path: .fg/extensions/Blink
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone Farratto/ResistanceIsFutile
      uses: actions/checkout@v4
      with:
        repository: Farratto/ResistanceIsFutile
        path: .fg/extensions/ResistanceIsFutile
        fetch-depth: 0
    - name: Clone Farratto/ZWhisperFGU
      uses: actions/checkout@v4
      with:
        repository: Farratto/ZWhisperFGU
        path: .fg/extensions/ZWhisperFGU
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone Farratto/InitiativeNanny
      uses: actions/checkout@v4
      with:
        repository: Farratto/InitiativeNanny
        path: .fg/extensions/InitiativeNanny
        fetch-depth: 0
    - name: Clone Farratto/StepCounter
      uses: actions/checkout@v4
      with:
        repository: Farratto/StepCounter
        path: .fg/extensions/StepCounter
        fetch-depth: 0
        token: ${{ secrets.ACTIONS }}
    - name: Clone Farratto/OpticalReferendum
      uses: actions/checkout@v4
      with:
        repository: Farratto/OpticalReferendum
        path: .fg/extensions/OpticalReferendum
        fetch-depth: 0
    - name: Clone Farratto/corerpg-combat-highlighter
      uses: actions/checkout@v4
      with:
        repository: Farratto/corerpg-combat-highlighter
        path: .fg/extensions/corerpg-combat-highlighter
        fetch-depth: 0

    # Processing
    - name: Generate new .luacheckrc
      uses: FG-Unofficial-Developers-Guild/action-generate-luacheckrc@main
      with:
        std: '+dnd2e+dnd35e+dnd4e+dnd5e+pfrpg+pfrpg2+sfrpg'

    - name: Create pull request
      uses: peter-evans/create-pull-request@v7
      with:
        title: Update .luacheckrc
        commit-message: "The latest .luacheckrc config build from targeted repos."
        branch: update-luacheckrc
        delete-branch: true
        token: ${{ secrets.ACTIONS }}
